server:
  port: 8081
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/GT?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: root
    password: 
mybatis:
  type-aliases-package: com.koreaIT.Game_Together.vo
riot:
  api:
    key: RGAPI-a30fbeb6-e2c9-4e45-99b2-b38cd84efda0
  server:
    url:
      kr: https://kr.api.riotgames.com
      asia: https://asia.api.riotgames.com