server:
  port: 8081
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1GB
  mail:
    host: smtp.gmail.com
    port: 587
    username: mailtestjbh@gmail.com
    password: 구글 앱 비밀번호 입력
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/GT?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: root
    password: 
mybatis:
  type-aliases-package: com.koreaIT.Game_Together.vo
riot:
  api:
    key: RGAPI-309596f8-1bcb-48c4-95ad-8be7e57151cb
  server:
    url:
      kr: https://kr.api.riotgames.com
      asia: https://asia.api.riotgames.com
custom:
  siteName: Game_Together
  siteMainUri: http://localhost:8081
  emailFrom: no-reply@localhost
  emailFromName: Game_Together
file:
  dir: C:/devJBH/sts-4.18.1.RELEASE-workspace/upload
coolsms:
  api:
    key: coolsms API Key 입력
    secret: coolsms API Secret 입력